apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-trace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trace
  template:
    metadata:
      labels:
        app: trace
    spec:
      containers:
      - name: sample-trace 
        image: gcr.io/dukeng-opencensus/sample-trace
        ports:
        - containerPort: 8080
        env:
            - name: PORT
              value: "8080"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                    fieldPath: metadata.namespace
